/*
 * types/v1/service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package rest

type V1LogFilter struct {
	ContractAddress *V1NullableString `json:"contractAddress,omitempty"`
	ChainId         int64             `json:"chainId,omitempty"`
	BlockNumber     *V1NullableUint64 `json:"blockNumber,omitempty"`
	TxHash          *V1NullableString `json:"txHash,omitempty"`
	TxIndex         *V1NullableUint64 `json:"txIndex,omitempty"`
	BlockHash       *V1NullableString `json:"blockHash,omitempty"`
	Index           *V1NullableUint64 `json:"index,omitempty"`
	Confirmed       *V1NullableBool   `json:"confirmed,omitempty"`
}
