/*
 * types/v1/service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package rest

type V1StreamLogsRequest struct {
	Filter    *V1LogFilter `json:"filter,omitempty"`
	FromBlock string       `json:"fromBlock,omitempty"`
	ToBlock   string       `json:"toBlock,omitempty"`
}
