{
 "title": "Bridge",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Omnirpc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Age",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "block_age", "legendFormat": "{{chain_id}}" }
   ]
  },
  {
   "title": "Omnirpc Block Age",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by(chain_id) (last_over_time(block_age[365d]))",
     "legendFormat": "{{chain_id}} "
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gas Balances (Validators)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "gas_balance{eoa_address=\"0x230A1AC45690B9Ae1176389434610B9526d2f21b\", instance!=\"192.168.8.22:9999\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Transaction Count Per Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(chain_id) (nonce{eoa_address=\"0x230A1AC45690B9Ae1176389434610B9526d2f21b\"})",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  { "title": "Message Bus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pending Heroes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "avg by(chain_name) (dfk_pending_heroes)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Gas Balances (Message Bus)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "gas_balance{eoa_address=\"0xAA920f7b9039e556d2442113f1fd339e4927Dd9A\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Transaction Count Per Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(chain_id) (nonce{name=\"messenger\"})",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  { "title": "CCTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Gas Balances (CCTP)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "gas_balance{name=\"cctp\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Transaction Count Per Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "avg by(chain_id) (nonce{name=\"cctp\"})",
     "legendFormat": "{{chain_id}}"
    }
   ]
  }
 ]
}