// Code generated by "stringer -type=RPCType"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Stable-0]
	_ = x[Auxiliary-1]
}

const _RPCType_name = "StableAuxiliary"

var _RPCType_index = [...]uint8{0, 6, 15}

func (i RPCType) String() string {
	if i >= RPCType(len(_RPCType_index)-1) {
		return "RPCType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RPCType_name[_RPCType_index[i]:_RPCType_index[i+1]]
}
