rpc_url: 'https://rpc.interoperability.institute/confirmations/1/rpc/'
scribe_url: 'https://scribe.interoperability.institute/graphql'
bridge_config_address: '0x5217c83ca75559B1f8a8803824E5b7ac233A12a1'
bridge_config_chain_id: 1
chains:
  - chain_id: 1
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x2796317b0fF8538F253012862c06787Adfb8cEb6'
      - cctp: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
  - chain_id: 42161
    avg_block_time: 1
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x6F4e8eBa4D337f874Ab57478AcC2Cb5BACdc19c9'
      - cctp: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
  - chain_id: 1313161554
    avg_block_time: 3
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
  - chain_id: 43114
    avg_block_time: 3
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xC05e61d0E7a63D27546389B7aD62FdFf5A91aACE'
      - cctp: '0xfB2Bfc368a7edfD51aa2cbEC513ad50edEa74E84'
  - chain_id: 288
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x432036208d2717394d2614d6697c46DF3Ed69540'
  - chain_id: 56
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xd123f70AE324d34A9E76b67a27bf77593bA8749f'
  - chain_id: 250
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
  - chain_id: 1666600000
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
  - chain_id: 137
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x8F5BBB2BB8c2Ee94639E55d5F41de9b4839C1280'
  - chain_id: 10
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
  - chain_id: 1284
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x84A420459cd31C3c34583F67E0f0fB191067D32f'
  - chain_id: 1285
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xaeD5b25BE1c3163c907a471082640450F928DDFE'
  - chain_id: 53935
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xE05c976d3f045D0E6E7A6f61083d98A15603cF6A'
  - chain_id: 25
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xE27BFf97CE92C3e1Ff7AA9f86781FDd6D48F5eE9'
  - chain_id: 1088
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x06Fea8513FF03a0d3f61324da709D4cf06F42A5c'
  - chain_id: 8217
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xAf41a65F786339e7911F4acDAD6BD49426F2Dc6b'
  - chain_id: 7700
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xDde5BEC4815E1CeCf336fb973Ca578e8D83606E0'
  - chain_id: 2000
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0x9508BF380c1e6f751D97604732eF1Bae6673f299'
  - chain_id: 8453
    avg_block_time: 13
    get_logs_range: 256
    get_logs_batch_amount: 2
    contracts:
      - bridge: '0xf07d1C752fAb503E47FEF309bf14fbDD3E867089'
