# Team Yaml
coverage:
  round: down
  precision: 5

ignore:
# go generated extensions
  - "*_generated.go"  # ignore folders and all its contents
  - "*.abigen.go"       # wildcards accepted
  - "*_string.go"         # glob accepted
  - "*_string.go"         # glob accepted
# solidity test files
  - 'packages/contracts/test/*'
