project_name: git-changes-action

monorepo:
  tag_prefix: contrib/git-changes-action/
  dir: contrib/git-changes-action/

builds:
  # Linux AMD64
  - id: git-changes-action
    binary: git-changes-action
    ldflags: -installsuffix static
    env:
      - CGO_ENABLED=0
    main: main.go
    flags:
      - -trimpath
    tags:
      - netgo
      - osusergo
    goos:
      - linux
    goarch:
      - amd64

# add a source archive at release time
source:
  enabled: true

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}'
    files:
      - README.md

checksum:
  name_template: checksums.txt

# Add a changelog
changelog:
  sort: asc

dockers:
  # Docker AMD64
  - goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/synapsecns/sanguine/git-changes-action:latest'
      - 'ghcr.io/synapsecns/sanguine/git-changes-action:{{ .FullCommit }}'
      - 'ghcr.io/synapsecns/sanguine/git-changes-action:{{ .Tag }}'
    build_flag_templates:
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
    dockerfile: ../../docker/git-changes-action.Dockerfile
    ids:
      - git-changes-action

# track sizes
report_sizes: true

# modified timestamps
metadata:
  # Set the modified timestamp on the metadata files.
  #
  # Templates: allowed.
  mod_timestamp: '{{ .CommitTimestamp }}'

# produce software bill of lading
sboms:
  - artifacts: archive

