[book]
title = "Synapse Contracts"
language = "en"
description = "Synapse Contracts"

[output.html]
git-repository-url = "https://github.com/synapsecns/sanguine/tree/master/packages/contracts-core"
edit-url = "https://github.com/synapsecns/sanguine/edit/master/packages/contracts-core/{path}"
