apiVersion: v1
kind: Service
metadata:
  name: {{ include "promexporter.fullname" . }}
  labels:
    {{- include "promexporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "promexporter.selectorLabels" . | nindent 4 }}
