# yaml-language-server: $schema=https://coderabbit.ai/integrations/coderabbit-overrides.v2.json

language: 'en'
early_access: true
reviews:
  auto_review:
    enabled: true
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
    drafts: true

  path_filters:
    - '!**abigen.go'
    - '!**metadata.go'
    - '!**pb.go'
    - '!**/bundle/*'
    - '!**/generated/*'


chat:
  auto_reply: true

