version: '2'
run:
  tests: true
linters:
  default: all
  disable:
    - contextcheck
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - godox
    - gomodguard
    - gomoddirectives
    - ireturn
    - lll
    - mnd
    - nlreturn
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - spancheck
    - tagliatelle
    - testpackage
    - testifylint
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    gocritic:
      disabled-checks:
        - appendAssign
    govet:
      enable:
        - shadow
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - revive
          - staticcheck
        path: _test\.go
      - linters:
          - wrapcheck
        path: export_test\.go
        text: should not use dot imports
      - linters:
          - revive
        path: contracts/
        text: and that stutters; consider calling this
      - linters:
          - wrapcheck
        path: ethergo/example/*
      - linters:
          - wrapcheck
        path: testutil/*
      - linters:
          - staticcheck
        path: ethergo/*
        text: SA1019
      - linters:
          - cyclop
        path: \.resolvers\.go
      - linters:
          - mnd
          - staticcheck
        path: signoz/*
      - linters:
          - cyclop
          - forcetypeassert
          - revive
          - staticcheck
          - wrapcheck
        path: example/*
    paths:
      - .*\\.abigen\\.go$
      - .*\\.metadata\\.go$
      - .*\\.pb\\.go$
      - .*_gen.go$
      - grpc/client/rest/*
      - bundle/*
      - generated/*
      - otelginmetrics/*
issues:
  new-from-rev: f34c91245633f7fbf49ad95d6c70bf667ce53c23
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - .*\\.abigen\\.go$
      - .*\\.metadata\\.go$
      - .*\\.pb\\.go$
      - .*_gen.go$
      - grpc/client/rest/*
      - bundle/*
      - generated/*
      - otelginmetrics/*
