ignore: |
  **/node_modules/**
  **/charts/**
  **/swagger.yaml
  **/openapi.yaml
  index.yaml

rules:
  document-start:
    present: false
  quoted-strings:
    quote-type: single
    required: false
