apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "synapse-node.fullname" . }}-{{ .Release.Name }}
  labels:
    app: {{ include "synapse-node.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ toYaml .Values.configurationFile | indent 2 }}
