{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "synapse-node.serviceAccountName" . }}
  labels:
{{ include "synapse-node.labels" . | indent 4 }}
{{- with .Values.serviceAccount.secrets }}
secrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
{{- end -}}
