import {
  BOBA_ETH_SWAP_TOKEN,
  ARBITRUM_ETH_SWAP_TOKEN,
  OPTIMISM_ETH_SWAP_TOKEN,
  AVALANCHE_AVETH_SWAP_TOKEN,
  FANTOM_WETH_SWAP_TOKEN,
  HARMONY_ONEETH_SWAP_TOKEN,
  METIS_WETH_SWAP_TOKEN,
  CANTO_WETH_SWAP_TOKEN,
} from '@constants/tokens/ethswap'

import {
  ETH_POOL_SWAP_TOKEN,
  BSC_POOL_SWAP_TOKEN,
  POLYGON_POOL_SWAP_TOKEN,
  FANTOM_POOL_SWAP_TOKEN,
  BOBA_POOL_SWAP_TOKEN,
  AVALANCHE_POOL_SWAP_TOKEN,
  ARBITRUM_POOL_SWAP_TOKEN,
  HARMONY_POOL_SWAP_TOKEN,
  AURORA_TS_POOL_SWAP_TOKEN,

  FANTOM_3POOL_SWAP_TOKEN,
  ARBITRUM_3POOL_SWAP_TOKEN,
} from '@constants/tokens/poolswap'
import { HARMONY_AVAX_SWAP_TOKEN } from './tokens/avaxswap'


export const PRICE_UNITS_INDEX = {
  [ETH_POOL_SWAP_TOKEN.poolName]:       'USD',
  [BSC_POOL_SWAP_TOKEN.poolName]:       'USD',
  [POLYGON_POOL_SWAP_TOKEN.poolName]:   'USD',
  [FANTOM_POOL_SWAP_TOKEN.poolName]:    'USD',
  [BOBA_POOL_SWAP_TOKEN.poolName]:      'USD',
  [AVALANCHE_POOL_SWAP_TOKEN.poolName]: 'USD',
  [ARBITRUM_POOL_SWAP_TOKEN.poolName]:  'USD',
  [HARMONY_POOL_SWAP_TOKEN.poolName]:   'USD',
  [AURORA_TS_POOL_SWAP_TOKEN.poolName]:    'USD',

  [FANTOM_3POOL_SWAP_TOKEN.poolName]:   'USD',
  [ARBITRUM_3POOL_SWAP_TOKEN.poolName]: 'USD',

  [FANTOM_WETH_SWAP_TOKEN.poolName]:     'ETH',
  [BOBA_ETH_SWAP_TOKEN.poolName]:        'ETH',
  [ARBITRUM_ETH_SWAP_TOKEN.poolName]:    'ETH',
  [OPTIMISM_ETH_SWAP_TOKEN.poolName]:    'ETH',
  [AVALANCHE_AVETH_SWAP_TOKEN.poolName]: 'ETH',
  [HARMONY_ONEETH_SWAP_TOKEN.poolName]:  'ETH',
  [METIS_WETH_SWAP_TOKEN.poolName]:      'ETH',
  [CANTO_WETH_SWAP_TOKEN.poolName]:      'ETH',


  [HARMONY_AVAX_SWAP_TOKEN.poolName]: 'AVAX',
}


