{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sinner.fullname" . }}
  labels:
    {{- include "sinner.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sinner.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  jobLabel: app.kubernetes.io/name
{{- end }}
