apiVersion: v1
kind: Service
metadata:
  name: {{ include "sinner.fullname" . }}
  labels:
    {{- include "sinner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "sinner.selectorLabels" . | nindent 4 }}
    sinner-type: server
