// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	bridge "github.com/synapsecns/sanguine/services/explorer/types/bridge"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"

	swap "github.com/synapsecns/sanguine/services/explorer/types/swap"
)

// ConsumerDB is an autogenerated mock type for the ConsumerDB type
type ConsumerDB struct {
	mock.Mock
}

// DB provides a mock function with given fields:
func (_m *ConsumerDB) DB() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// ReadBlockNumberByChainID provides a mock function with given fields: ctx, eventType, chainID
func (_m *ConsumerDB) ReadBlockNumberByChainID(ctx context.Context, eventType int8, chainID uint32) (*uint64, error) {
	ret := _m.Called(ctx, eventType, chainID)

	var r0 *uint64
	if rf, ok := ret.Get(0).(func(context.Context, int8, uint32) *uint64); ok {
		r0 = rf(ctx, eventType, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uint64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int8, uint32) error); ok {
		r1 = rf(ctx, eventType, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreEvent provides a mock function with given fields: ctx, bridgeEvent, swapEvent, chainID, tokenID
func (_m *ConsumerDB) StoreEvent(ctx context.Context, bridgeEvent bridge.EventLog, swapEvent swap.EventLog, chainID uint32, tokenID *string) error {
	ret := _m.Called(ctx, bridgeEvent, swapEvent, chainID, tokenID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bridge.EventLog, swap.EventLog, uint32, *string) error); ok {
		r0 = rf(ctx, bridgeEvent, swapEvent, chainID, tokenID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewConsumerDB interface {
	mock.TestingT
	Cleanup(func())
}

// NewConsumerDB creates a new instance of ConsumerDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConsumerDB(t mockConstructorTestingTNewConsumerDB) *ConsumerDB {
	mock := &ConsumerDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
