{{- if .Values.remote.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "executor.fullname" . }}-runRemote
  labels:
    {{- include "executor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.remote.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "executor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.remote.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/" $.Chart.Name "-configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "executor.selectorLabels" . | nindent 8 }}
        executor-type: remote
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "executor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.remote.podSecurityContext | nindent 8 }}
    {{- if .Values.files }}
      initContainers:
        - name: copy-{{ .Release.Name }}-config
          image: busybox
          command: [ 'sh', '-c', 'cp -v /configmap/* /config/' ]
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: {{ .Release.Name }}-config
              mountPath: /config
        {{- if .Values.remote.extraInitContainers }}
        {{- toYaml .Values.remote.extraInitContainers | nindent 8 }}
        {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.remote.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.remote.env }}
          env:
            {{- toYaml .Values.remote.env | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
        {{- if .Values.files }}
          volumeMounts:
            - name: configmap
              mountPath: /config
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.remote.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.remote.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.remote.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.files }}
        - name: {{ .Release.Name }}-config
          emptyDir: { }
        - name: configmap
          configMap:
            name: {{ include "executor.fullname" . }}-{{ .Release.Name }}
        {{- end }}
{{- end }}
