// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package l1gateway

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DepositETHEvent-1]
	_ = x[DepositERC20Event-2]
	_ = x[FinalizeWithdrawETHEvent-3]
	_ = x[FinalizeWithdrawERC20Event-4]
}

const _EventType_name = "DepositETHEventDepositERC20EventFinalizeWithdrawETHEventFinalizeWithdrawERC20Event"

var _EventType_index = [...]uint8{0, 15, 32, 56, 82}

func (i EventType) String() string {
	i -= 1
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
