{
 "title": "RFQ Relayer",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "relayer",
    "label": "Relayer address",
    "query": {
     "query": "label_values(inventory_balance,relayer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RFQ Relayer Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is the rfq. It is used to track metrics for the rfq relayer. \n\nIf you update this dashboard please be sure to update the [docs](https://bridge-docs-theta.vercel.app/docs/rfq/Relayer/#observability) at `docs/bridge/` and the dashboard folder in `services/rfq/relayer/dashbords/dashboard.json`"
   }
  },
  {
   "title": "Relayer ETH balances",
   "type": "timeseries",
   "description": "ETH balances of the RFQ relayer by chain.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(inventory_balance{token_name=\"ETH\",relayer=\"$relayer\"}) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayer USDC balances",
   "type": "timeseries",
   "description": "USDC balances of the RFQ relayer by chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "avg(inventory_balance{token_name=\"USD Coin\",relayer=\"$relayer\"}) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Quote Sizing",
   "type": "timeseries",
   "description": "Displays the ETH quote amount for each origin -> destination path.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "avg(quote_amount{origin_token_name=\"ETH\", dest_token_name=\"ETH\"}) by (origin_chain_id, dest_chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Quote Sizing",
   "type": "timeseries",
   "description": "Displays the USDC quote amount for each origin -> destination path.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(quote_amount{origin_token_name=\"USD Coin\"} / 1e6) by (origin_chain_id, destination_chain_id)",
     "legendFormat": "{{origin_chain_id}} to {{destination_chain_id}} "
    }
   ]
  },
  {
   "title": "Request Statuses",
   "type": "timeseries",
   "description": "Displays the count of any non-terminal QuoteRequestStatus values over time.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by(status) (status_count{wallet=\"$relayer\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}