{
 "title": "RFQ Relayer",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "relayer",
    "label": "Relayer address",
    "query": {
     "query": "label_values(inventory_balance_sum,relayer)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Relayer ETH balances",
   "type": "timeseries",
   "description": "ETH balances of the RFQ relayer by chain.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(inventory_balance_sum{token_name=\"ETH\",relayer=\"$relayer\"}[1m]) / rate(inventory_balance_count{token_name=\"ETH\",relayer=\"$relayer\"}[1m])) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relayer USDC balances",
   "type": "timeseries",
   "description": "USDC balances of the RFQ relayer by chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(inventory_balance_sum{token_name=\"USD Coin\",relayer=\"$relayer\"}[1m]) / rate(inventory_balance_count{token_name=\"USD Coin\",relayer=\"$relayer\"}[1m])) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETH Quote Sizing",
   "type": "timeseries",
   "description": "Displays the ETH quote amount for each origin -> destination path.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(quote_amount_sum{origin_token_name=\"ETH\",relayer=\"$relayer\"}[5m])) by (origin_chain_id, destination_chain_id) \n/ \nsum(rate(quote_amount_count{origin_token_name=\"ETH\",relayer=\"$relayer\"}[5m])) by (origin_chain_id, destination_chain_id)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "USDC Quote Sizing",
   "type": "timeseries",
   "description": "Displays the USDC quote amount for each origin -> destination path.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(quote_amount_sum{origin_token_name=\"USD Coin\",relayer=\"$relayer\"}[5m])) by (origin_chain_id, destination_chain_id) \n/ \nsum(rate(quote_amount_count{origin_token_name=\"USD Coin\",relayer=\"$relayer\"}[5m])) by (origin_chain_id, destination_chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Submitter Transactions",
   "type": "timeseries",
   "description": "Displays a rolling average of the number of transactions pending in the submitter, by chain.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(rate(num_pending_txes_sum{wallet=\"$relayer\"}[15m]) / rate(num_pending_txes_count{wallet=\"$relayer\"}[15m])) by (chain_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nonces",
   "type": "timeseries",
   "description": "Displays the latest on-chain nonce for the submitter wallet by chain.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "avg(avg_over_time(current_nonce_sum{wallet=\"$relayer\"}[5m]) / avg_over_time(current_nonce_count{wallet=\"$relayer\"}[5m])) by (chain_id)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}