// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InterchainTransaction struct {
	Sent     *InterchainTransactionSent     `json:"sent,omitempty"`
	Received *InterchainTransactionReceived `json:"received,omitempty"`
}

type InterchainTransactionReceived struct {
	TransactionID *string `json:"transactionId,omitempty"`
	DbNonce       *int    `json:"dbNonce,omitempty"`
	EntryIndex    *int    `json:"entryIndex,omitempty"`
	SrcChainID    *int    `json:"srcChainId,omitempty"`
	SrcSender     *string `json:"srcSender,omitempty"`
	DstReceiver   *string `json:"dstReceiver,omitempty"`
	Raw           *string `json:"raw,omitempty"`
}

type InterchainTransactionSent struct {
	TransactionID   *string `json:"transactionId,omitempty"`
	DbNonce         *int    `json:"dbNonce,omitempty"`
	EntryIndex      *int    `json:"entryIndex,omitempty"`
	DstChainID      *int    `json:"dstChainId,omitempty"`
	SrcSender       *string `json:"srcSender,omitempty"`
	DstReceiver     *string `json:"dstReceiver,omitempty"`
	VerificationFee *string `json:"verificationFee,omitempty"`
	ExecutionFee    *string `json:"executionFee,omitempty"`
	Options         *string `json:"options,omitempty"`
	Message         *string `json:"message,omitempty"`
	Raw             *string `json:"raw,omitempty"`
}
