// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/data/sync": {
            "post": {
                "description": "blacklist an address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "blacklist an address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application ID",
                        "name": "appid",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Timestamp of the request",
                        "name": "timestamp",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "A unique nonce for the request",
                        "name": "nonce",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Query string parameters included in the request",
                        "name": "queryString",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature for request validation",
                        "name": "signature",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
