// autogenerated file

package exporters

// iOtelRecorder ...
type iOtelRecorder interface {
	// Virtual Price Metrics.
	RecordVPrice(chainid int, vPrice float64)
	// Token Balance Metrics.
	RecordBridgeGasBalance(chainid int, gasBalance float64)
	RecordTokenBalance(chainID int, tokenData tokenData)
	// DFK Metrics.
	RecordStuckHeroCount(stuckHeroes int64)
	// Submitter stats.
	RecordSubmitterStats(chainid int, nonce int64, balance float64, gasCheckName string)
}
