project_name: ethergo

monorepo:
  tag_prefix: ethergo/
  dir: ethergo/

builds:
  - skip: true

# add a source archive at release time
source:
  enabled: true

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}'
    replacements:
      amd64: x86_64
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md

checksum:
  name_template: checksums.txt

# Add a changelog
changelog:
  sort: asc
