client:
  package: client
  filename: ./client/client.go # Where should any generated client go?

query:
  - 'client/queries/*.graphql' # Where are all the query files located?

####
# Note: these are ignored and pulled from gqlgen.yml in our generator
# modifying them will have no effect, but they cannot be removed since
# they are validated
###
schema:
  - 'server/graph/schema/*.graphql' # Where are all the schema files located?
