// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package swap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenSwapEvent-0]
	_ = x[AddLiquidityEvent-1]
	_ = x[RemoveLiquidityEvent-2]
	_ = x[RemoveLiquidityOneEvent-3]
	_ = x[RemoveLiquidityImbalanceEvent-4]
	_ = x[NewAdminFeeEvent-5]
	_ = x[NewSwapFeeEvent-6]
	_ = x[RampAEvent-7]
	_ = x[StopRampAEvent-8]
	_ = x[FlashLoanEvent-9]
	_ = x[TokenSwapUnderlyingEvent-10]
}

const _EventType_name = "TokenSwapEventAddLiquidityEventRemoveLiquidityEventRemoveLiquidityOneEventRemoveLiquidityImbalanceEventNewAdminFeeEventNewSwapFeeEventRampAEventStopRampAEventFlashLoanEventTokenSwapUnderlyingEvent"

var _EventType_index = [...]uint8{0, 14, 31, 51, 74, 103, 119, 134, 144, 158, 172, 196}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
