apiVersion: v2
name: agents
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.23

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: mysql
    version: "9.3.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.enabled
  - name: omnirpc
    version: "0.2.5"
    repository: "file://../omnirpc/"
    condition: omnirpc.enabled
  - name: scribe
    version: "0.2.9"
    repository: "file://../scribe/"
    condition: scribe.enabled
  - name: jaeger
    version: 0.69.1
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
