global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'go-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9000']
    metrics_path: '/metrics'
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8098']
