// autogenerated file

package origin

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
)

// IOriginCaller ...
type IOriginCaller interface {
	// SYNAPSEDOMAIN is a free data retrieval call binding the contract method 0xbf61e67e.
	//
	// Solidity: function SYNAPSE_DOMAIN() view returns(uint32)
	SYNAPSEDOMAIN(opts *bind.CallOpts) (uint32, error)
	// AllAgents is a free data retrieval call binding the contract method 0x64ecb518.
	//
	// Solidity: function allAgents(uint32 _domain) view returns(address[])
	AllAgents(opts *bind.CallOpts, _domain uint32) ([]common.Address, error)
	// AllDomains is a free data retrieval call binding the contract method 0x6f225878.
	//
	// Solidity: function allDomains() view returns(uint32[] domains_)
	AllDomains(opts *bind.CallOpts) ([]uint32, error)
	// AmountAgents is a free data retrieval call binding the contract method 0x32254098.
	//
	// Solidity: function amountAgents(uint32 _domain) view returns(uint256)
	AmountAgents(opts *bind.CallOpts, _domain uint32) (*big.Int, error)
	// AmountDomains is a free data retrieval call binding the contract method 0x61b0b357.
	//
	// Solidity: function amountDomains() view returns(uint256)
	AmountDomains(opts *bind.CallOpts) (*big.Int, error)
	// GetAgent is a free data retrieval call binding the contract method 0x1d82873b.
	//
	// Solidity: function getAgent(uint32 _domain, uint256 _agentIndex) view returns(address)
	GetAgent(opts *bind.CallOpts, _domain uint32, _agentIndex *big.Int) (common.Address, error)
	// GetDomain is a free data retrieval call binding the contract method 0x1a7a98e2.
	//
	// Solidity: function getDomain(uint256 _domainIndex) view returns(uint32)
	GetDomain(opts *bind.CallOpts, _domainIndex *big.Int) (uint32, error)
	// IsActiveAgent is a free data retrieval call binding the contract method 0x0958117d.
	//
	// Solidity: function isActiveAgent(uint32 _domain, address _account) view returns(bool)
	IsActiveAgent(opts *bind.CallOpts, _domain uint32, _account common.Address) (bool, error)
	// IsActiveAgent0 is a free data retrieval call binding the contract method 0x65e1e466.
	//
	// Solidity: function isActiveAgent(address _account) view returns(bool isActive, uint32 domain)
	IsActiveAgent0(opts *bind.CallOpts, _account common.Address) (struct {
		IsActive bool
		Domain   uint32
	}, error)
	// IsActiveDomain is a free data retrieval call binding the contract method 0x4f5dbc0d.
	//
	// Solidity: function isActiveDomain(uint32 _domain) view returns(bool)
	IsActiveDomain(opts *bind.CallOpts, _domain uint32) (bool, error)
	// IsValidState is a free data retrieval call binding the contract method 0xa9dcf22d.
	//
	// Solidity: function isValidState(bytes _statePayload) view returns(bool isValid)
	IsValidState(opts *bind.CallOpts, _statePayload []byte) (bool, error)
	// LocalDomain is a free data retrieval call binding the contract method 0x8d3638f4.
	//
	// Solidity: function localDomain() view returns(uint32)
	LocalDomain(opts *bind.CallOpts) (uint32, error)
	// Owner is a free data retrieval call binding the contract method 0x8da5cb5b.
	//
	// Solidity: function owner() view returns(address)
	Owner(opts *bind.CallOpts) (common.Address, error)
	// SuggestLatestState is a free data retrieval call binding the contract method 0xc0b56f7c.
	//
	// Solidity: function suggestLatestState() view returns(bytes stateData)
	SuggestLatestState(opts *bind.CallOpts) ([]byte, error)
	// SuggestState is a free data retrieval call binding the contract method 0xb4596b4b.
	//
	// Solidity: function suggestState(uint32 _nonce) view returns(bytes stateData)
	SuggestState(opts *bind.CallOpts, _nonce uint32) ([]byte, error)
	// SystemRouter is a free data retrieval call binding the contract method 0x529d1549.
	//
	// Solidity: function systemRouter() view returns(address)
	SystemRouter(opts *bind.CallOpts) (common.Address, error)
	// Version is a free data retrieval call binding the contract method 0x54fd4d50.
	//
	// Solidity: function version() view returns(string versionString)
	Version(opts *bind.CallOpts) (string, error)
}
