chains:
  42:
  43:
  44:
omnirpc_url: http://omnirpc:9001
database:
  type: 'sqlite'
  dsn: '/tmp/committee'
signer:
  type: 'File'
  file: '/config/committee-signer.txt'
submitter_config:
  chains:
    42:
      supports_eip_1559: true
      gas_estimate: 7500000
    43:
      gas_bump_percentage: 40
      is_l2: true
      gas_estimate: 7500000
    44:
      gas_bump_percentage: 40
      is_l2: true
      gas_estimate: 7500000
should_relay: true
bootstrap_peers:
  - /ip4/10.0.0.121/tcp/12346/p2p/16Uiu2HAm48u7E6mDZbTRiuBD3ug54o4HHmeTsQAyG2yUWGoDp3g3
  - /ip4/127.0.0.1/tcp/12346/p2p/16Uiu2HAm48u7E6mDZbTRiuBD3ug54o4HHmeTsQAyG2yUWGoDp3g3
p2p_port: 12346
use_peer_id: false
