chains:
  42:
    rpcs:
      - http://0.0.0.0:8545/
      # - http://chain_a:8545/
    confirmations: 1
  43:
    rpcs:
      - http://0.0.0.0:8545/
      # - http://chain_b:8545/
    confirmations: 1
  44:
    rpcs:
      - http://0.0.0.0:8545/
      # - http://chain_c:8545/
    confirmations: 1
# port to run on
port: 9001
# expressed in seconds
refreshInterval: 60
client_type: resty
