chains:
  42:
    rpcs:
      - http://0.0.0.0:8042
    confirmations: 0
  43:
    rpcs:
      - http://0.0.0.0:8043/
    confirmations: 0
  44:
    rpcs:
      - http://0.0.0.0:8044/
    confirmations: 0
# port to run on
port: 9001
# expressed in seconds
refreshInterval: 60
client_type: 'resty'
