{{- if .Values.indexer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "explorer.fullname" . }}-indexer
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "explorer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.indexer.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "explorer.selectorLabels" . | nindent 8 }}
        {{- include "explorer.commonLabels" . | nindent 8 }}
        explorer-type: indexer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "explorer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.indexer.podSecurityContext | nindent 8 }}
    {{- if .Values.files }}
      initContainers:
        - name: copy-{{ .Release.Name }}-config
          image: busybox
          command: ['sh', '-c', 'cp -v /configmap/* /config/']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: {{ .Release.Name }}-config
              mountPath: /config
        {{- if .Values.indexer.extraInitContainers }}
        {{- toYaml .Values.indexer.extraInitContainers | nindent 8 }}
        {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.indexer.args }}
          args:
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with .Values.indexer.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.indexer.env }}
          env:
            {{- toYaml .Values.indexer.env | nindent 12 }}
          {{- end }}
    {{- if .Values.files }}
          volumeMounts:
            - name: configmap
              mountPath: /config
        {{- end }}
        {{- if .Values.indexer.extraContainers }}
        {{- toYaml .Values.indexer.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.indexer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.indexer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.files }}
        - name: {{ .Release.Name }}-config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ include "explorer.fullname" . }}-{{ .Release.Name }}
        {{- end }}
{{- end }}
