apiVersion: v1
kind: Service
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.server.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "explorer.selectorLabels" . | nindent 4 }}
    explorer-type: server
