{{- if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rfq.fullname" . }}
  labels:
    app: {{ include "rfq.name" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: {{ .Release.Service }}
data:
{{ tpl (toYaml .Values.files) . | indent 2 }}
{{- end }}
