client:
  package: client
  filename: ./client.go # Where should any generated client go?

query:
  - 'queries/*.graphql' # Where are all the query files located?

model:
  filename: model/models_gen.go
  package: model

####
# Note: these are ignored and pulled from gqlgen.yml in our generator
# modifying them will have no effect, but they cannot be removed since
# they are validated
###
schema:
  - 'schema/*.graphql' # Where are all the schema files located?
