[default]
optimizer = true
optimizer_runs = 1000000
auto_detect_solc = true
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]

[ci]
verbosity = 4

# See more config options https://github.com/gakonst/foundry/tree/master/config