[profile.default]
optimizer = true
optimizer_runs = 1000000
auto_detect_solc = true
src = "contracts"
out = "artifacts"
libs = ["../../node_modules", "node_modules", "lib"]

[profile.ci]
verbosity = 4
fuzz_runs = 1000

# See more config options https://github.com/gakonst/foundry/tree/master/config
