coverage:
  status:
    project:
      default:
        target: '80%'
        threshold: '1%'
    patch:
      default:
        target: '80%'

ignore:
  - '**/testdata/**'
  - '**/mocks/**'
  - '**/*_test.go'
  - '**/cmd/**'
  - '**/docs/**'
