version: 2

project_name: golang-ci-lint

monorepo:
  tag_prefix: contrib/golang-ci-lint/
  dir: contrib/golang-ci-lint/

builds:
  - id: golang-ci-lint
    binary: golang-ci-lint
    gcflags:
      - all=-dwarflocationlists=true
    ldflags:
      - -s -w -extldflags "-static"
    tags:
      - netgo
      - osusergo
    env:
      - CGO_ENABLED=0
    main: main.go
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/synapsecns/sanguine/golang-ci-lint:latest'
      - 'ghcr.io/synapsecns/sanguine/golang-ci-lint:{{ .FullCommit }}'
      - 'ghcr.io/synapsecns/sanguine/golang-ci-lint:{{ .Tag }}'
    build_flag_templates:
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.name={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--label=org.opencontainers.image.licenses=MIT'
      - '--label=org.opencontainers.image.vendor=Synapse Labs'
      - '--label=org.opencontainers.image.documentation=https://github.com/synapsecns/sanguine/tree/master/contrib/golang-ci-lint'
    dockerfile: ../../docker/golang-ci-lint.Dockerfile
    ids:
      - golang-ci-lint

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

source:
  enabled: true

sboms:
  - artifacts: archive

report_sizes: true

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
