/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export type PoolTokenStruct = {
  isWeth: PromiseOrValue<boolean>
  token: PromiseOrValue<string>
}

export type PoolTokenStructOutput = [boolean, string] & {
  isWeth: boolean
  token: string
}

export type PoolStruct = {
  pool: PromiseOrValue<string>
  lpToken: PromiseOrValue<string>
  tokens: PoolTokenStruct[]
}

export type PoolStructOutput = [string, string, PoolTokenStructOutput[]] & {
  pool: string
  lpToken: string
  tokens: PoolTokenStructOutput[]
}

export type SwapQueryStruct = {
  swapAdapter: PromiseOrValue<string>
  tokenOut: PromiseOrValue<string>
  minAmountOut: PromiseOrValue<BigNumberish>
  deadline: PromiseOrValue<BigNumberish>
  rawParams: PromiseOrValue<BytesLike>
}

export type SwapQueryStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  string
] & {
  swapAdapter: string
  tokenOut: string
  minAmountOut: BigNumber
  deadline: BigNumber
  rawParams: string
}

export type BridgeTokenStruct = {
  symbol: PromiseOrValue<string>
  token: PromiseOrValue<string>
}

export type BridgeTokenStructOutput = [string, string] & {
  symbol: string
  token: string
}

export type DestRequestStruct = {
  symbol: PromiseOrValue<string>
  amountIn: PromiseOrValue<BigNumberish>
}

export type DestRequestStructOutput = [string, BigNumber] & {
  symbol: string
  amountIn: BigNumber
}

export declare namespace LocalBridgeConfig {
  export type BridgeTokenConfigStruct = {
    id: PromiseOrValue<string>
    token: PromiseOrValue<string>
    tokenType: PromiseOrValue<BigNumberish>
    bridgeToken: PromiseOrValue<string>
    bridgeFee: PromiseOrValue<BigNumberish>
    minFee: PromiseOrValue<BigNumberish>
    maxFee: PromiseOrValue<BigNumberish>
  }

  export type BridgeTokenConfigStructOutput = [
    string,
    string,
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    id: string
    token: string
    tokenType: number
    bridgeToken: string
    bridgeFee: BigNumber
    minFee: BigNumber
    maxFee: BigNumber
  }
}

export interface SynapseRouterInterface extends utils.Interface {
  functions: {
    'adapterSwap(address,address,uint256,address,bytes)': FunctionFragment
    'addToken(string,address,uint8,address,uint256,uint256,uint256)': FunctionFragment
    'addTokens((string,address,uint8,address,uint256,uint256,uint256)[])': FunctionFragment
    'allPools()': FunctionFragment
    'bridge(address,uint256,address,uint256,(address,address,uint256,uint256,bytes),(address,address,uint256,uint256,bytes))': FunctionFragment
    'bridgeTokens()': FunctionFragment
    'bridgeTokensAmount()': FunctionFragment
    'calculateAddLiquidity(address,uint256[])': FunctionFragment
    'calculateBridgeFee(address,uint256)': FunctionFragment
    'calculateRemoveLiquidity(address,uint256)': FunctionFragment
    'calculateSwap(address,uint8,uint8,uint256)': FunctionFragment
    'calculateWithdrawOneToken(address,uint256,uint8)': FunctionFragment
    'config(address)': FunctionFragment
    'fee(address)': FunctionFragment
    'getAmountOut(address,address,uint256)': FunctionFragment
    'getConnectedBridgeTokens(address)': FunctionFragment
    'getDestinationAmountOut((string,uint256)[],address)': FunctionFragment
    'getOriginAmountOut(address,string[],uint256)': FunctionFragment
    'owner()': FunctionFragment
    'poolInfo(address)': FunctionFragment
    'poolTokens(address)': FunctionFragment
    'poolsAmount()': FunctionFragment
    'removeToken(address)': FunctionFragment
    'removeTokens(address[])': FunctionFragment
    'renounceOwnership()': FunctionFragment
    'setAllowance(address,address,uint256)': FunctionFragment
    'setSwapQuoter(address)': FunctionFragment
    'setTokenConfig(address,uint8,address)': FunctionFragment
    'setTokenFee(address,uint256,uint256,uint256)': FunctionFragment
    'swap(address,address,uint256,(address,address,uint256,uint256,bytes))': FunctionFragment
    'swapQuoter()': FunctionFragment
    'symbolToToken(string)': FunctionFragment
    'synapseBridge()': FunctionFragment
    'tokenToSymbol(address)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'adapterSwap'
      | 'addToken'
      | 'addTokens'
      | 'allPools'
      | 'bridge'
      | 'bridgeTokens'
      | 'bridgeTokensAmount'
      | 'calculateAddLiquidity'
      | 'calculateBridgeFee'
      | 'calculateRemoveLiquidity'
      | 'calculateSwap'
      | 'calculateWithdrawOneToken'
      | 'config'
      | 'fee'
      | 'getAmountOut'
      | 'getConnectedBridgeTokens'
      | 'getDestinationAmountOut'
      | 'getOriginAmountOut'
      | 'owner'
      | 'poolInfo'
      | 'poolTokens'
      | 'poolsAmount'
      | 'removeToken'
      | 'removeTokens'
      | 'renounceOwnership'
      | 'setAllowance'
      | 'setSwapQuoter'
      | 'setTokenConfig'
      | 'setTokenFee'
      | 'swap'
      | 'swapQuoter'
      | 'symbolToToken'
      | 'synapseBridge'
      | 'tokenToSymbol'
      | 'transferOwnership'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'adapterSwap',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'addToken',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'addTokens',
    values: [LocalBridgeConfig.BridgeTokenConfigStruct[]]
  ): string
  encodeFunctionData(functionFragment: 'allPools', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'bridge',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      SwapQueryStruct,
      SwapQueryStruct
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'bridgeTokens',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'bridgeTokensAmount',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'calculateAddLiquidity',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>[]]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateBridgeFee',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateRemoveLiquidity',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateSwap',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateWithdrawOneToken',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'config',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'fee',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'getAmountOut',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'getConnectedBridgeTokens',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'getDestinationAmountOut',
    values: [DestRequestStruct[], PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'getOriginAmountOut',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>[],
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'poolInfo',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'poolTokens',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'poolsAmount',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'removeToken',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'removeTokens',
    values: [PromiseOrValue<string>[]]
  ): string
  encodeFunctionData(
    functionFragment: 'renounceOwnership',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'setAllowance',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'setSwapQuoter',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'setTokenConfig',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'setTokenFee',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'swap',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      SwapQueryStruct
    ]
  ): string
  encodeFunctionData(functionFragment: 'swapQuoter', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'symbolToToken',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'synapseBridge',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'tokenToSymbol',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string

  decodeFunctionResult(functionFragment: 'adapterSwap', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addToken', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'addTokens', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'allPools', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'bridge', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'bridgeTokens',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'bridgeTokensAmount',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateAddLiquidity',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateBridgeFee',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateRemoveLiquidity',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateSwap',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'calculateWithdrawOneToken',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'config', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'fee', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getAmountOut',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getConnectedBridgeTokens',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getDestinationAmountOut',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getOriginAmountOut',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolInfo', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolTokens', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'poolsAmount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'removeToken', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'removeTokens',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'renounceOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setAllowance',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setSwapQuoter',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setTokenConfig',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'setTokenFee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'swap', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'swapQuoter', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'symbolToToken',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'synapseBridge',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'tokenToSymbol',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result

  events: {
    'OwnershipTransferred(address,address)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export interface OwnershipTransferredEventObject {
  previousOwner: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>

export interface SynapseRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: SynapseRouterInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    adapterSwap(
      to: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      tokenOut: PromiseOrValue<string>,
      rawParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    addToken(
      symbol: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    addTokens(
      tokens: LocalBridgeConfig.BridgeTokenConfigStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    allPools(
      overrides?: CallOverrides
    ): Promise<[PoolStructOutput[]] & { pools: PoolStructOutput[] }>

    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      originQuery: SwapQueryStruct,
      destQuery: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    bridgeTokens(
      overrides?: CallOverrides
    ): Promise<[string[]] & { tokens: string[] }>

    bridgeTokensAmount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>

    calculateAddLiquidity(
      pool: PromiseOrValue<string>,
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    calculateBridgeFee(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { feeAmount: BigNumber }>

    calculateRemoveLiquidity(
      pool: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]] & { amountsOut: BigNumber[] }>

    calculateSwap(
      pool: PromiseOrValue<string>,
      tokenIndexFrom: PromiseOrValue<BigNumberish>,
      tokenIndexTo: PromiseOrValue<BigNumberish>,
      dx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>

    calculateWithdrawOneToken(
      pool: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      tokenIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amountOut: BigNumber }>

    config(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number, string] & { tokenType: number; bridgeToken: string }>

    fee(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        bridgeFee: number
        minFee: BigNumber
        maxFee: BigNumber
      }
    >

    getAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[SwapQueryStructOutput]>

    getConnectedBridgeTokens(
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [BridgeTokenStructOutput[]] & { tokens: BridgeTokenStructOutput[] }
    >

    getDestinationAmountOut(
      requests: DestRequestStruct[],
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [SwapQueryStructOutput[]] & { destQueries: SwapQueryStructOutput[] }
    >

    getOriginAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenSymbols: PromiseOrValue<string>[],
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [SwapQueryStructOutput[]] & { originQueries: SwapQueryStructOutput[] }
    >

    owner(overrides?: CallOverrides): Promise<[string]>

    poolInfo(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>

    poolTokens(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[PoolTokenStructOutput[]] & { tokens: PoolTokenStructOutput[] }>

    poolsAmount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { amount: BigNumber }>

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    removeTokens(
      tokens: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setAllowance(
      token: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setSwapQuoter(
      _swapQuoter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setTokenConfig(
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setTokenFee(
      token: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    swap(
      to: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      query: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    swapQuoter(overrides?: CallOverrides): Promise<[string]>

    symbolToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>

    synapseBridge(overrides?: CallOverrides): Promise<[string]>

    tokenToSymbol(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  adapterSwap(
    to: PromiseOrValue<string>,
    tokenIn: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    tokenOut: PromiseOrValue<string>,
    rawParams: PromiseOrValue<BytesLike>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  addToken(
    symbol: PromiseOrValue<string>,
    token: PromiseOrValue<string>,
    tokenType: PromiseOrValue<BigNumberish>,
    bridgeToken: PromiseOrValue<string>,
    bridgeFee: PromiseOrValue<BigNumberish>,
    minFee: PromiseOrValue<BigNumberish>,
    maxFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  addTokens(
    tokens: LocalBridgeConfig.BridgeTokenConfigStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  allPools(overrides?: CallOverrides): Promise<PoolStructOutput[]>

  bridge(
    to: PromiseOrValue<string>,
    chainId: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    originQuery: SwapQueryStruct,
    destQuery: SwapQueryStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  bridgeTokens(overrides?: CallOverrides): Promise<string[]>

  bridgeTokensAmount(overrides?: CallOverrides): Promise<BigNumber>

  calculateAddLiquidity(
    pool: PromiseOrValue<string>,
    amounts: PromiseOrValue<BigNumberish>[],
    overrides?: CallOverrides
  ): Promise<BigNumber>

  calculateBridgeFee(
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  calculateRemoveLiquidity(
    pool: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>

  calculateSwap(
    pool: PromiseOrValue<string>,
    tokenIndexFrom: PromiseOrValue<BigNumberish>,
    tokenIndexTo: PromiseOrValue<BigNumberish>,
    dx: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  calculateWithdrawOneToken(
    pool: PromiseOrValue<string>,
    tokenAmount: PromiseOrValue<BigNumberish>,
    tokenIndex: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  config(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[number, string] & { tokenType: number; bridgeToken: string }>

  fee(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [number, BigNumber, BigNumber] & {
      bridgeFee: number
      minFee: BigNumber
      maxFee: BigNumber
    }
  >

  getAmountOut(
    tokenIn: PromiseOrValue<string>,
    tokenOut: PromiseOrValue<string>,
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SwapQueryStructOutput>

  getConnectedBridgeTokens(
    tokenOut: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BridgeTokenStructOutput[]>

  getDestinationAmountOut(
    requests: DestRequestStruct[],
    tokenOut: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<SwapQueryStructOutput[]>

  getOriginAmountOut(
    tokenIn: PromiseOrValue<string>,
    tokenSymbols: PromiseOrValue<string>[],
    amountIn: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<SwapQueryStructOutput[]>

  owner(overrides?: CallOverrides): Promise<string>

  poolInfo(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string]>

  poolTokens(
    pool: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<PoolTokenStructOutput[]>

  poolsAmount(overrides?: CallOverrides): Promise<BigNumber>

  removeToken(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  removeTokens(
    tokens: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setAllowance(
    token: PromiseOrValue<string>,
    spender: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setSwapQuoter(
    _swapQuoter: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setTokenConfig(
    token: PromiseOrValue<string>,
    tokenType: PromiseOrValue<BigNumberish>,
    bridgeToken: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setTokenFee(
    token: PromiseOrValue<string>,
    bridgeFee: PromiseOrValue<BigNumberish>,
    minFee: PromiseOrValue<BigNumberish>,
    maxFee: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  swap(
    to: PromiseOrValue<string>,
    token: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    query: SwapQueryStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  swapQuoter(overrides?: CallOverrides): Promise<string>

  symbolToToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>

  synapseBridge(overrides?: CallOverrides): Promise<string>

  tokenToSymbol(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    adapterSwap(
      to: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      tokenOut: PromiseOrValue<string>,
      rawParams: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    addToken(
      symbol: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>

    addTokens(
      tokens: LocalBridgeConfig.BridgeTokenConfigStruct[],
      overrides?: CallOverrides
    ): Promise<void>

    allPools(overrides?: CallOverrides): Promise<PoolStructOutput[]>

    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      originQuery: SwapQueryStruct,
      destQuery: SwapQueryStruct,
      overrides?: CallOverrides
    ): Promise<void>

    bridgeTokens(overrides?: CallOverrides): Promise<string[]>

    bridgeTokensAmount(overrides?: CallOverrides): Promise<BigNumber>

    calculateAddLiquidity(
      pool: PromiseOrValue<string>,
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateBridgeFee(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateRemoveLiquidity(
      pool: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>

    calculateSwap(
      pool: PromiseOrValue<string>,
      tokenIndexFrom: PromiseOrValue<BigNumberish>,
      tokenIndexTo: PromiseOrValue<BigNumberish>,
      dx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateWithdrawOneToken(
      pool: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      tokenIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    config(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[number, string] & { tokenType: number; bridgeToken: string }>

    fee(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [number, BigNumber, BigNumber] & {
        bridgeFee: number
        minFee: BigNumber
        maxFee: BigNumber
      }
    >

    getAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SwapQueryStructOutput>

    getConnectedBridgeTokens(
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BridgeTokenStructOutput[]>

    getDestinationAmountOut(
      requests: DestRequestStruct[],
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<SwapQueryStructOutput[]>

    getOriginAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenSymbols: PromiseOrValue<string>[],
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<SwapQueryStructOutput[]>

    owner(overrides?: CallOverrides): Promise<string>

    poolInfo(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>

    poolTokens(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PoolTokenStructOutput[]>

    poolsAmount(overrides?: CallOverrides): Promise<BigNumber>

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>

    removeTokens(
      tokens: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>

    renounceOwnership(overrides?: CallOverrides): Promise<void>

    setAllowance(
      token: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    setSwapQuoter(
      _swapQuoter: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    setTokenConfig(
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    setTokenFee(
      token: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    swap(
      to: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      query: SwapQueryStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    swapQuoter(overrides?: CallOverrides): Promise<string>

    symbolToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>

    synapseBridge(overrides?: CallOverrides): Promise<string>

    tokenToSymbol(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {
    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
  }

  estimateGas: {
    adapterSwap(
      to: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      tokenOut: PromiseOrValue<string>,
      rawParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    addToken(
      symbol: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    addTokens(
      tokens: LocalBridgeConfig.BridgeTokenConfigStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    allPools(overrides?: CallOverrides): Promise<BigNumber>

    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      originQuery: SwapQueryStruct,
      destQuery: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    bridgeTokens(overrides?: CallOverrides): Promise<BigNumber>

    bridgeTokensAmount(overrides?: CallOverrides): Promise<BigNumber>

    calculateAddLiquidity(
      pool: PromiseOrValue<string>,
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateBridgeFee(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateRemoveLiquidity(
      pool: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateSwap(
      pool: PromiseOrValue<string>,
      tokenIndexFrom: PromiseOrValue<BigNumberish>,
      tokenIndexTo: PromiseOrValue<BigNumberish>,
      dx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    calculateWithdrawOneToken(
      pool: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      tokenIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    config(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    fee(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getConnectedBridgeTokens(
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getDestinationAmountOut(
      requests: DestRequestStruct[],
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getOriginAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenSymbols: PromiseOrValue<string>[],
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    poolInfo(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    poolTokens(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    poolsAmount(overrides?: CallOverrides): Promise<BigNumber>

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    removeTokens(
      tokens: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setAllowance(
      token: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setSwapQuoter(
      _swapQuoter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setTokenConfig(
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setTokenFee(
      token: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    swap(
      to: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      query: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    swapQuoter(overrides?: CallOverrides): Promise<BigNumber>

    symbolToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    synapseBridge(overrides?: CallOverrides): Promise<BigNumber>

    tokenToSymbol(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    adapterSwap(
      to: PromiseOrValue<string>,
      tokenIn: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      tokenOut: PromiseOrValue<string>,
      rawParams: PromiseOrValue<BytesLike>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    addToken(
      symbol: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    addTokens(
      tokens: LocalBridgeConfig.BridgeTokenConfigStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    allPools(overrides?: CallOverrides): Promise<PopulatedTransaction>

    bridge(
      to: PromiseOrValue<string>,
      chainId: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      originQuery: SwapQueryStruct,
      destQuery: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    bridgeTokens(overrides?: CallOverrides): Promise<PopulatedTransaction>

    bridgeTokensAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    calculateAddLiquidity(
      pool: PromiseOrValue<string>,
      amounts: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    calculateBridgeFee(
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    calculateRemoveLiquidity(
      pool: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    calculateSwap(
      pool: PromiseOrValue<string>,
      tokenIndexFrom: PromiseOrValue<BigNumberish>,
      tokenIndexTo: PromiseOrValue<BigNumberish>,
      dx: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    calculateWithdrawOneToken(
      pool: PromiseOrValue<string>,
      tokenAmount: PromiseOrValue<BigNumberish>,
      tokenIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    config(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    fee(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenOut: PromiseOrValue<string>,
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getConnectedBridgeTokens(
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getDestinationAmountOut(
      requests: DestRequestStruct[],
      tokenOut: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getOriginAmountOut(
      tokenIn: PromiseOrValue<string>,
      tokenSymbols: PromiseOrValue<string>[],
      amountIn: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    poolInfo(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    poolTokens(
      pool: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    poolsAmount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    removeToken(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    removeTokens(
      tokens: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setAllowance(
      token: PromiseOrValue<string>,
      spender: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setSwapQuoter(
      _swapQuoter: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setTokenConfig(
      token: PromiseOrValue<string>,
      tokenType: PromiseOrValue<BigNumberish>,
      bridgeToken: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setTokenFee(
      token: PromiseOrValue<string>,
      bridgeFee: PromiseOrValue<BigNumberish>,
      minFee: PromiseOrValue<BigNumberish>,
      maxFee: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    swap(
      to: PromiseOrValue<string>,
      token: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      query: SwapQueryStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    swapQuoter(overrides?: CallOverrides): Promise<PopulatedTransaction>

    symbolToToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    synapseBridge(overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenToSymbol(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
