// Code generated by "stringer -type=ActiveQuoteRequestStatus"; DO NOT EDIT.

package db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Received-1]
	_ = x[Pending-2]
	_ = x[Expired-3]
	_ = x[Fulfilled-4]
}

const _ActiveQuoteRequestStatus_name = "ReceivedPendingExpiredFulfilled"

var _ActiveQuoteRequestStatus_index = [...]uint8{0, 8, 15, 22, 31}

func (i ActiveQuoteRequestStatus) String() string {
	i -= 1
	if i >= ActiveQuoteRequestStatus(len(_ActiveQuoteRequestStatus_index)-1) {
		return "ActiveQuoteRequestStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ActiveQuoteRequestStatus_name[_ActiveQuoteRequestStatus_index[i]:_ActiveQuoteRequestStatus_index[i+1]]
}
