// Code generated by "stringer -type=ActiveQuoteResponseStatus"; DO NOT EDIT.

package db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Considered-1]
	_ = x[Returned-2]
	_ = x[PastExpiration-3]
	_ = x[Malformed-4]
	_ = x[Duplicate-5]
}

const _ActiveQuoteResponseStatus_name = "ConsideredReturnedPastExpirationMalformedDuplicate"

var _ActiveQuoteResponseStatus_index = [...]uint8{0, 10, 18, 32, 41, 50}

func (i ActiveQuoteResponseStatus) String() string {
	i -= 1
	if i >= ActiveQuoteResponseStatus(len(_ActiveQuoteResponseStatus_index)-1) {
		return "ActiveQuoteResponseStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ActiveQuoteResponseStatus_name[_ActiveQuoteResponseStatus_index[i]:_ActiveQuoteResponseStatus_index[i+1]]
}
