chains:
  - chain_id: 42161
    rpc_url: https://rpc.interoperability.institute/confirmations/1/rpc/42161
    required_confirmations: 50
    contracts:
      - address: 0xA67b7147DcE20D6F25Fd9ABfBCB1c3cA74E11f0B
        start_block: 6262095
  - chain_id: 1
    rpc_url: https://rpc.interoperability.institute/confirmations/1/rpc/1
    required_confirmations: 50
    contracts:
      - address: 0xFE986b20d34df3Aa9fA2e4d18b8EBe5AC6c753b0
        start_block: 12656274
refresh_rate: 0
rpc_url: https://rpc.interoperability.institute/confirmations
