chains:
  - chain_id: 10
    rpc_url: https://rpc.interoperability.institute/confirmations/1/rpc/10
    required_confirmations: 50
    contracts:
      - address: 0x84A420459cd31C3c34583F67E0f0fB191067D32f
        start_block: 30814
      - address: 0x8745773CC6e70577819BB76f51FA7640cece505F
        start_block: 30715
      - address: 0xaC9b0B65e7CFc1DD482Ed9249a44e58c9C9086ed
        start_block: 203044
  - chain_id: 1
    rpc_url: https://rpc.interoperability.institute/confirmations/1/rpc/1
    required_confirmations: 50
    contracts:
      - address: 0xFE986b20d34df3Aa9fA2e4d18b8EBe5AC6c753b0
        start_block: 12656274
      - address: 0x5217c83ca75559B1f8a8803824E5b7ac233A12a1
        start_block: 14259367
      - address: 0x2796317b0fF8538F253012862c06787Adfb8cEb6
        start_block: 13033669
refresh_rate: 0
rpc_url: https://rpc.interoperability.institute/confirmations
