// Code generated by "stringer -type=EventType"; DO NOT EDIT.

package summit

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AttestationSavedEvent-0]
}

const _EventType_name = "AttestationSavedEvent"

var _EventType_index = [...]uint8{0, 21}

func (i EventType) String() string {
	if i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
