{{- if .Values.executor_remote_fresh.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agents.fullname" . }}-executor-remote
  labels:
    {{- include "agents.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.executor_remote_fresh.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/" $.Chart.Name "-configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agents.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agents.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.executor_remote_fresh.podSecurityContext | nindent 8 }}
    {{- if .Values.executor_remote_fresh_files }}
      initContainers:
        - name: copy-{{ .Release.Name }}-config
          image: busybox
          command: [ 'sh', '-c', 'cp -v /configmap/* /config/' ]
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: {{ .Release.Name }}-config
              mountPath: /config
        {{- if .Values.executor_remote_fresh.extraInitContainers }}
        {{- toYaml .Values.executor_remote_fresh.extraInitContainers | nindent 8 }}
        {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "executor-run"
            - "--config=/config/config.yaml"
            - "--scribe-type=remote"
            - "--db=mysql"
            - "--path=root:MysqlPassword@tcp(executor-mysql:3306)/executor"
            - "--scribe-port=80"
            - "--scribe-url=executor-scribe-server"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.executor_remote_fresh.env }}
          env:
            {{- toYaml .Values.executor_remote_fresh.env | nindent 12 }}
          {{- end }}
        {{- if .Values.executor_remote_fresh_files }}
          volumeMounts:
            - name: configmap
              mountPath: /config
        {{- end }}
        {{- if .Values.executor_remote_fresh.extraContainers }}
        {{- toYaml .Values.executor_remote_fresh.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.executor_remote_fresh.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor_remote_fresh.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor_remote_fresh.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.executor_remote_fresh_files }}
        - name: {{ .Release.Name }}-config
          emptyDir: { }
        - name: configmap
          configMap:
            name: {{ include "agents.fullname" . }}-{{ .Release.Name }}
        {{- end }}
{{- end}}
