{{- if .Values.executor_embedded.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agents.fullname" . }}-executor-embedded
  labels:
    {{- include "agents.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agents.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.executor_embedded.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Chart.Name "/templates/" $.Chart.Name "-configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agents.selectorLabels" . | nindent 8 }}
{{/*        executor-type: embedded*/}}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agents.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.executor_embedded.podSecurityContext | nindent 8 }}
    {{- if .Values.executor_embedded_files }}
      initContainers:
        - name: copy-{{ .Release.Name }}-config
          image: busybox
          command: [ 'sh', '-c', 'cp -v /configmap/* /config/' ]
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: {{ .Release.Name }}-config
              mountPath: /config
        {{- if .Values.executor_embedded.extraInitContainers }}
        {{- toYaml .Values.executor_embedded.extraInitContainers | nindent 8 }}
        {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.executor_embedded.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.executor_embedded.env }}
          env:
            {{- toYaml .Values.executor_embedded.env | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
        {{- if .Values.executor_embedded_files }}
          volumeMounts:
            - name: configmap
              mountPath: /config
        {{- end }}
        {{- if .Values.executor_embedded.extraContainers }}
        {{- toYaml .Values.executor_embedded.extraContainers | nindent 8 }}
        {{- end }}
      {{- with .Values.executor_embedded.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor_embedded.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.executor_embedded.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.executor_embedded_files }}
        - name: {{ .Release.Name }}-config
          emptyDir: { }
        - name: configmap
          configMap:
            name: {{ include "agents.fullname" . }}-{{ .Release.Name }}
        {{- end }}
{{- end}}
