name: Setup NodeJS
inputs:
  nvmrc_path:
    default: ".nvmrc"
    description: Set to a relative path to use a different .nvmrc file
description: Setup pnpm for contracts
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "pnpm"
        cache-dependency-path: "contracts/pnpm-lock.yaml"

    - if: ${{ inputs.prod == 'false' }}
      name: Install dependencies
      shell: bash
      run: pnpm i
      working-directory: contracts

    - if: ${{ inputs.prod == 'true' }}
      name: Install prod dependencies
      shell: bash
      run: pnpm i --prod
      working-directory: contracts
