# This is the root golangci-lint configuration for the tools package
linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - unused
    - gosimple
  disable:
    - deadcode  # deprecated
    - structcheck  # deprecated
    - varcheck  # deprecated

linters-settings:
  unused:
    check-exported: false  # Don't warn about exported unused functions in test files
  staticcheck:
    checks:
      - 'all'
      - '-SA1019'  # Ignore deprecation warnings
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - shadow  # Too many false positives

issues:
  exclude-rules:
    # Exclude unused warnings for test files
    - path: _test\.go$
      linters:
        - unused
      text: 'imported and not used'
    # Exclude certain patterns in test files
    - path: _test\.go$
      text: 'testify/suite'
      linters:
        - unused
    - path: _test\.go$
      text: 'testify/require'
      linters:
        - unused
    - path: _test\.go$
      text: 'testing'
      linters:
        - unused
    # Exclude file permission checks in test files
    - path: _test\.go$
      linters:
        - gosec
      text: 'G302: Expect file permissions'

run:
  timeout: 5m
  tests: true
  build-tags:
    - integration
    - tools
