project_name: tools

monorepo:
  tag_prefix: tools/
  dir: tools/

builds:
  # Linux AMD64
  - id: abigen-amd64
    binary: abigen-amd64
    env:
      - CGO_CFLAGS=-I/usr/local/include
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lsnappy  -lzstd -lbz2
    # see: https://github.com/cosmos/iavl/pull/465/files
    ldflags:
      - -s -w
    main: abigen/main.go
    flags:
      - -tags=builtin_static,rocksdb,static
    goos:
      - linux
    goarch:
      - amd64

  - id: modulecopier-amd64
    binary: modulecopier-amd64
    env:
      - CGO_CFLAGS=-I/usr/local/include
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lsnappy  -lzstd -lbz2
    # see: https://github.com/cosmos/iavl/pull/465/files
    ldflags:
      - -s -w
    main: modulecopier/main.go
    flags:
      - -tags=builtin_static,rocksdb,static
    goos:
      - linux
    goarch:
      - amd64

  - id: bundle-amd64
    binary: bundle-amd64
    env:
      # probably not neccesary for this module
      - CGO_CFLAGS=-I/usr/local/include
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lsnappy  -lzstd -lbz2
    # see: https://github.com/cosmos/iavl/pull/465/files
    ldflags:
      - -s -w
    main: bundle/main.go
    flags:
      - -tags=builtin_static,rocksdb,static # probably not neccesary for this module
    goos:
      - linux
    goarch:
      - amd64

  - id: resolver-amd64
    binary: resolver-amd64
    env:
      # probably not neccesary for this module
      - CGO_CFLAGS=-I/usr/local/include
      - CGO_ENABLED=1
      - CGO_LDFLAGS=-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lsnappy  -lzstd -lbz2
    # see: https://github.com/cosmos/iavl/pull/465/files
    ldflags:
      - -s -w
    main: revertresolver/main.go
    flags:
      - -tags=builtin_static,rocksdb,static # probably not neccesary for this module
    goos:
      - linux
    goarch:
      - amd64
# add a source archive at release time
source:
  enabled: true

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{.ProjectName}}-{{.Version}}_{{.Os}}_{{.Arch}}'
    files:
      - abigen/README.md
      - modulecopier/README.md

checksum:
  name_template: checksums.txt

# Add a changelog
changelog:
  sort: asc

# track sizes
report_sizes: true

# modified timestamps
metadata:
  # Set the modified timestamp on the metadata files.
  #
  # Templates: allowed.
  mod_timestamp: '{{ .CommitTimestamp }}'

# produce software bill of lading
sboms:
  - artifacts: archive

