// Code generated by "stringer -type=QuoteRequestStatus"; DO NOT EDIT.

package reldb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Seen-1]
	_ = x[NotEnoughInventory-2]
	_ = x[CommittedPending-3]
	_ = x[CommittedConfirmed-4]
	_ = x[RelayStarted-5]
	_ = x[RelayCompleted-6]
}

const _QuoteRequestStatus_name = "SeenNotEnoughInventoryCommittedPendingCommittedConfirmedRelayStartedRelayCompleted"

var _QuoteRequestStatus_index = [...]uint8{0, 4, 22, 38, 56, 68, 82}

func (i QuoteRequestStatus) String() string {
	i -= 1
	if i >= QuoteRequestStatus(len(_QuoteRequestStatus_index)-1) {
		return "QuoteRequestStatus(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _QuoteRequestStatus_name[_QuoteRequestStatus_index[i]:_QuoteRequestStatus_index[i+1]]
}
