// Code generated by "stringer -type=RebalanceStatus"; DO NOT EDIT.

package reldb

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RebalanceInitiated-0]
	_ = x[RebalancePending-1]
	_ = x[RebalanceCompleted-2]
}

const _RebalanceStatus_name = "RebalanceInitiatedRebalancePendingRebalanceCompleted"

var _RebalanceStatus_index = [...]uint8{0, 18, 34, 52}

func (i RebalanceStatus) String() string {
	if i >= RebalanceStatus(len(_RebalanceStatus_index)-1) {
		return "RebalanceStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RebalanceStatus_name[_RebalanceStatus_index[i]:_RebalanceStatus_index[i+1]]
}
