{
 "title": "Submitter",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wallet",
    "label": "Wallet",
    "query": {
     "query": "label_values(num_pending_txes,wallet)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Submitter Dashboard",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This is the submitter dashboard. It is used to track metrics common to submitter. \n\nIf you update this dashboard please be sure to update the [docs](https://bridge-docs-theta.vercel.app/docs/Services/Submitter) at `docs/bridge/` and the dashboard folder in `ethergo/submitter/dashboard.json`"
   }
  },
  { "title": "Submitter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Pending Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "max by(chain_id) (num_pending_txes{wallet=\"$wallet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nonce",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "max by(chain_id) (current_nonce{wallet=\"$wallet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oldest Pending TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(chain_id) (oldest_pending_tx_seconds{wallet=\"$wallet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Confirmed Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by(chain_id) (confirmed_queue{wallet=\"$wallet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Balance Per Chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "max by(chain_id) (gas_balance{wallet=\"$wallet\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}