package replicamanager

//go:generate go run github.com/synapsecns/synapse-node/testutils/codegen/abigen generate --sol ../../../packages/contracts/flattened/ReplicaManager.sol --pkg replicamanager --sol-version 0.8.13 --filename replicamanager
// line after go:generate cannot be left blank

// here we generate some interfaces we use in for our mocks. TODO this should be automated in abigen for all contracts + be condensed
//go:generate go run github.com/vburenin/ifacemaker -f replicamanager.abigen.go -s ReplicaManagerCaller -i IReplicaManagerCaller -p replicamanager -o icaller_generated.go -c "autogenerated file"
//go:generate go run github.com/vburenin/ifacemaker -f replicamanager.abigen.go -s ReplicaManagerTransactor -i IReplicaManagerTransactor -p replicamanager -o itransactor_generated.go -c "autogenerated file"
//go:generate go run github.com/vburenin/ifacemaker -f replicamanager.abigen.go -s ReplicaManagerFilterer  -i IReplicaManagerFilterer  -p replicamanager  -o filterer_generated.go -c "autogenerated file"
//go:generate go run github.com/vektra/mockery/v2 --name IReplicaManager --output ./mocks --case=underscore
// last line must be null
