// Code generated by "stringer -type=DBType -linecomment"; DO NOT EDIT.

package dbcommon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mysql-0]
	_ = x[Sqlite-1]
	_ = x[Clickhouse-2]
}

const _DBType_name = "mysqlsqliteclickhouse"

var _DBType_index = [...]uint8{0, 5, 11, 21}

func (i DBType) String() string {
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return "DBType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
