name: Clear all Github actions caches
on:
  # must be manually triggered
  workflow_dispatch:

jobs:
  clear-caches:
    name: Delete all caches
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v1
        with:
          comment_on_pr: false
          proc_trace_sys_enable: true
          metric_frequency: 2
      - name: Clear caches
        uses: easimon/wipe-cache@main
