name: Combine Coverage

# We need to use workflow_dispatch here because workflow_on (auto triggering after a completed workflow, see: https://github.com/orgs/community/discussions/25288)
# only works on the default branch and maxes out at 3 runs for now. We use workflow_dispatch after jobs that require coverage to get around this
on: [push,pull_request]


jobs:
  # notify coveralls paralell jobs are finished running
  post-coverage:
    name: Mark Coveralls Complete
    runs-on: ubuntu-latest
    steps:
      # for an explanation on why we need two workflows, see: https://github.com/lewagon/wait-on-check-action/issues/25
      - name: Wait for Coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.sha }}
          check-regexp: Coverage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
          allowed-conclusions: success,skipped,cancelled
      - name: Wait for Coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name == 'pull_request'
        with:
          allowed-conclusions: success,skipped,cancelled
          ref: ${{ github.event.pull_request.head.sha }}
          check-regexp: Coverage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5

      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
