name: Combine Coverage

# We need to use workflow_dispatch here because workflow_on (auto triggering after a completed workflow, see: https://github.com/orgs/community/discussions/25288)
# only works on the default branch and maxes out at 3 runs for now. We use workflow_dispatch after jobs that require coverage to get around this
on: [push,pull_request]


jobs:
  # notify coveralls paralell jobs are finished running
  post-coverage:
    name: Mark Coveralls Complete
    runs-on: ubuntu-latest
    steps:
      - name: Wait for go coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.sha }}
          check-regexp: Coverage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Wait for go coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-regexp: Coverage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30


      # new checks (go), see: https://github.com/lewagon/wait-on-check-action/issues/25#issuecomment-1203747335
      - name: Wait for go coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.sha }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Wait for go coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      # new checks, see: https://github.com/lewagon/wait-on-check-action/issues/25#issuecomment-1203747335
      - name: Wait for foundry coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ github.sha }}
          check-name: check
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
      - name: Wait for foundry coverage to complete
        uses: lewagon/wait-on-check-action@v1.1.2
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: check
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30

      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
