name: Combine Coverage

# We need to use workflow_dispatch here because workflow_on (auto triggering after a completed workflow, see: https://github.com/orgs/community/discussions/25288)
# only works on the default branch and maxes out at 3 runs for now. We use workflow_dispatch after jobs that require coverage to get around this
on: [push,pull_request]


jobs:
  # notify coveralls paralell jobs are finished running
  post-coverage:
    name: Mark Coveralls Complete
    runs-on: ubuntu-latest
    steps:
      - name: Wait for foundry coverage to complete
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          running-workflow-name: 'Run Foundry Tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
          wait-interval: 20
      - name: Wait for go coverage to complete
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          running-workflow-name: 'Run Go Tests'
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 20
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
