name: Combiner

# TODO: maybe this should be a workflow run? https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions
on:
  workflow_run:
    workflows: ["Changeset integrity checker"] #["Go Workflows", "Foundry Tests"]

jobs:
  # notify coveralls paralell jobs are finished running
  post-coverage:
    name: Mark Coveralls Complete
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
