# TODO: maybe this should be a workflow run? https://stackoverflow.com/questions/58457140/dependencies-between-workflows-on-github-actions
on:
  pull_request:
  push:
    branches-ignore:
      - 'gh-pages'

# TODO: improve naming here
needs: [test,check]

name: Coverall

jobs:
  # notify coveralls paralell jobs are finished running
  post-coverage:
    name: Packages/contracts
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
