name: UI Cypress Integration Tests

on:
  push:
  pull_request:
    paths:
      - 'packages/synapse-interface/**'
      - '.github/workflows/cypress.yaml'

jobs:
  cypress-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs

      - name: Install dependencies
        run: yarn install
        working-directory: './packages/synapse-interface'

      - name: Install sdk-router
        run: yarn install
        working-directory: './packages/sdk-router'

      - name: Run Cypress tests
        run: yarn cypress:run
        working-directory: './packages/synapse-interface'
