name: 'Pre-build dev container image'
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.devcontainer/**'
      - '.github/workflows/devcontainer.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # always required
      packages: write
      # only required for private repos
      actions: read
      contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host


      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/synapsecns/sanguine-devcontainer
          # important: enabling caching will cause foundry not to be rebuild
          push: always
          noCache: true
      - name: Tag daily image
        run: |
          docker tag ghcr.io/synapsecns/sanguine-devcontainer:latest ghcr.io/synapsecns/sanguine-devcontainer:$(date +%Y-%m-%d)
          docker push ghcr.io/synapsecns/sanguine-devcontainer:$(date +%Y-%m-%d)
