name: Forge Build Size Check

on:
  push:
    paths:
      - 'packages/contracts-core/**'
      - '.github/workflows/foundry-build-check.yml'
  pull_request:
    paths:
      - 'packages/contracts-core/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node JS
        uses: ./.github/actions/setup-nodejs

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run forge build --sizes
        run: |
          forge build --sizes
        working-directory: packages/contracts-core
