name: 'Build Hyperliquid Node Image'
on:
  schedule:
    - cron: '30 1 * * *'  # Run daily at 1:30 UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Adjust branch as needed
      - feat/hl
    paths:
      - 'Dockerfile'
      - '.github/workflows/hyperliquid-node.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          repository: 'hyperliquid-dex/node'
          ref: 'main'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Hyperliquid Node Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/synapsecns/hyperliquid:latest
            ghcr.io/synapsecns/hyperliquid:testnet-latest
            ghcr.io/synapsecns/hyperliquid:testnet-${{ github.sha }}
            ghcr.io/synapsecns/hyperliquid:testnet-$(date +%Y-%m-%d)
          build-args: |
            CHAIN=Testnet

      - name: Tag with Date
        run: |
          TODAY=$(date +%Y-%m-%d)
          docker tag ghcr.io/synapsecns/hyperliquid:testnet-latest ghcr.io/synapsecns/hyperliquid:testnet-${TODAY}
          docker push ghcr.io/synapsecns/hyperliquid:testnet-${TODAY}
