name: 'Build Hyperliquid Node Images'
on:
  schedule:
    - cron: '30 1 * * *'  # Run daily at 1:30 UTC
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
      - feat/hl
      - fix/hyperliquid-arm64
    paths:
      - 'docker/hyperliquid.Dockerfile'
      - '.github/workflows/hyperliquid-node.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.set-date.outputs.date }}
    steps:
      - name: Set Date Tag
        id: set-date
        run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
    strategy:
      matrix:
        network: [testnet, mainnet]
        include:
          - network: testnet
            chain: Testnet
          - network: mainnet
            chain: Mainnet
    steps:
      - name: Git Checkout (Sanguine)
        uses: actions/checkout@v4

      - name: Git Checkout (Hyperliquid)
        uses: actions/checkout@v4
        with:
          repository: 'hyperliquid-dex/node'
          ref: 'main'
          path: 'hyperliquid-node'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push ${{ matrix.network }} Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/hyperliquid.Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ matrix.network == 'mainnet' && 'ghcr.io/synapsecns/hyperliquid:latest' || '' }}
            ghcr.io/synapsecns/hyperliquid:${{ matrix.network }}-latest
            ghcr.io/synapsecns/hyperliquid:${{ matrix.network }}-${{ github.sha }}
            ghcr.io/synapsecns/hyperliquid:${{ matrix.network }}-${{ needs.setup.outputs.date }}
          build-args: |
            CHAIN=${{ matrix.chain }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
