name: 'Pull Request Labeler'
on:
  pull_request:
    types: [opened, synchronize]
  push:


jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml
          sync-labels: true

  add-pr-labels:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: victorx64/pr-label@v0
        with:
          # Optional pattern used to limit paths.
          # Example: "'*.js' ':!*.spec.js' .".
          # See https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          git-pathspec: ":!*gen.go :!*generated.go"
