# fail if certain labels are present
name: Label Statuses
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  # fail if certain labels are present
  label-statuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: 'do not merge'

      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 0
          labels: 'needs go generate'
