name: 'Pull Request Labeler'
on:
  - pull_request_target

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler.yml
          sync-labels: true

      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/xs'
          xs_max_size: '50'
          s_label: 'size/s'
          s_max_size: '300'
          m_label: 'size/m'
          m_max_size: '1000'
          l_label: 'size/l'
          l_max_size: '10000000'
          # this is functionally disabled to avoid comments
          xl_label: 'size/xl'
          fail_if_xl: 'false'

      - uses: ppremk/lfs-warning@v3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Optional
          filesizelimit: 15MB

      - name: Add 'fe-release' label
        if: github.event.pull_request.base.ref == 'fe-release'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'fe-release'
