name: Code Scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'synapsecns'
    # these are pretty disruptive
#    permissions:
#      contents: write
#      pull-requests: write
#      checks: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
