name: Update gh pages

on:
  push:
    branches:
      - master
      - fix/sync-gh-pages

jobs:
  update-cms-master:
    name: Merge master into gh-pages after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'master'
          target: 'gh-pages'
