name: Tag
on:
  push:
    branches:
      - ci/version
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Bump version and push tag
        # TODO: change once https://github.com/anothrNick/github-tag-action/pull/167 is merged
        uses: nyoungstudios/github-tag-action@master
        env:
          # need to use another tag token (see https://github.com/orgs/community/discussions/27028#discussioncomment-3254360)
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: .*

      - name: Bump version and push tag
        # TODO: change once https://github.com/anothrNick/github-tag-action/pull/167 is merged
        uses: nyoungstudios/github-tag-action@master
        env:
          # need to use another tag token (see https://github.com/orgs/community/discussions/27028#discussioncomment-3254360)
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: .*
